[package]
name = "ptd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
csv = "1.1"
lettre = "0.9"
lettre_email = "0.9"
chrono = "*"