// crates for constructing & sending email
use lettre_email::EmailBuilder;
use lettre::smtp::authentication::Credentials;
use lettre::{SmtpClient, Transport};

// future: put these into a (pub) mod, rather than direct from lib.rs
use ptd::randomcode;
use ptd::datetime;
use ptd::posname;
use ptd::engname;
use ptd::gas;
use ptd::elec;
use ptd::water;
use ptd::yesno;

// save results to logfile.txt - append new line with each line of input.
// future: save to DB or blockchain (append only)

fn main() {
// Instantiates objects to be used in email.
	let position = posname();
	let engineer = engname();
	let safe = yesno();
	let g = gas();
	let l = elec();
	let w = water();
	let code = randomcode();
	let dt = datetime();
	
	println!("This permit will be emailed to the specified users.");
	
	let emailtext = format!(
	"\nThis email is from an automated inbox. Do not reply. 
	\nPermit to dig number: {} {} \n
	\nPosition name: {} \n
	\nEngineer name: {} \n
	\nIt is {} \n
	\nThe following services have been located: \n
	\n{}\n
	\n{}\n
	\n{}\n", 
	&code, &dt, &position, &engineer, &safe, &g, &l, &w //adds details from input functions to email text string.
	);
	
	let email = EmailBuilder::new() //creates new email item
        // DANGER ZONE
		.to("---------------")
		.to("------------")
        .from("------------")
		// DANGER ZONE
        .subject("Permit to dig")
        .text(emailtext)
		//.text("This permit applies to {}.",loc)
		//.text("This permit was generated by {}.",person)
		//.text("Is it safe to dig? {}.",safe)
        .build()
        .unwrap();
		
    let mut mailer = SmtpClient::new_simple("smtp.zoho.eu") //sends email via Smtp - the simplest way of doing this!
        .unwrap()
		// DANGER ZONE
        .credentials(Credentials::new("test@email".into(), "-----".into())) //Make sure not to expose your credentials.
		// DANGER ZONE
        .transport();

    let result = mailer.send(email.into());

    println!("{:?}", result);

}



// testing to come later, when more complex

//#[cfg(test)]
//mod tests {
//	#[test]
//	fn it_works() {
//		let result = 2 + 2;
//		assert_eq!(results, 4);
//	}
//}